#!/usr/bin/python
#-*- coding: utf-8 -*-
# File Name: iter.py
# Created Time: Mon May 11 00:29:28 2015

__author__ = 'Crayon Chaney <mmmmmcclxxvii@gmail.com>'

class fib(object):
    def __init__(self):
        self.a,self.b = 0,1
    def __iter__(self):
        return self

    def next(self):
        self.a,self.b = self.b,self.a+self.b
        if self.a > 100:
            raise StopIteration()
        return self


for i in fib():
    print i


